'use client'

import { FormEvent, useMemo, useState } from 'react'
import Link from 'next/link'
import { ArrowRight, Box, Check, ChevronDown, Heart, Menu, PackageCheck, Search, ShieldCheck, ShoppingBag, SlidersHorizontal, Users, X } from 'lucide-react'

type Product = { id:number; brand:string; name:string; price:number; size:string; condition:'Mint'|'Excellent'|'Good'|'Fair'; category:string; stock:number; tone:string; mark:string }
const products: Product[] = [
  {id:1,brand:'Stüssy',name:'Heavyweight Hoodie 1995',price:85,size:'XL',condition:'Excellent',category:'Tops',stock:1,tone:'from-[#565f4e] to-[#293029]',mark:'STÜSSY'},
  {id:2,brand:'Carhartt',name:'Work Pant Slate Grey',price:120,size:'32W',condition:'Excellent',category:'Bottoms',stock:2,tone:'from-[#77736d] to-[#343331]',mark:'WORKWEAR'},
  {id:3,brand:'Supreme',name:'Nuptse Jacket Red',price:680,size:'L',condition:'Good',category:'Outerwear',stock:1,tone:'from-[#a74433] to-[#3d2420]',mark:'SUPREME'},
  {id:4,brand:'Nike',name:'Air Jordan 1 Low OG Chicago 1992',price:2400,size:'10',condition:'Mint',category:'Footwear',stock:1,tone:'from-[#eee8df] to-[#b55239]',mark:'NIKE AIR'},
  {id:5,brand:'Dickies',name:'874 Black USA Made',price:45,size:'30W',condition:'Fair',category:'Bottoms',stock:3,tone:'from-[#353532] to-[#111110]',mark:'874'},
  {id:6,brand:"Levi's",name:'501 Indigo Deadstock',price:280,size:'32W',condition:'Mint',category:'Bottoms',stock:1,tone:'from-[#40526a] to-[#1e2939]',mark:'501'},
  {id:7,brand:'Stüssy',name:'Cream Embroidered Logo Tee',price:95,size:'M',condition:'Excellent',category:'Tops',stock:2,tone:'from-[#ddd3c5] to-[#9e917e]',mark:'STÜSSY'},
  {id:8,brand:'Porter',name:'Utility Shoulder Bag',price:145,size:'OS',condition:'Good',category:'Accessories',stock:1,tone:'from-[#4c4a3d] to-[#1f201d]',mark:'PORTER'}
]
const badge = {Mint:'bg-[#8b9a7c] text-white',Excellent:'bg-[#d6ddcf]',Good:'bg-[#e3c69c]',Fair:'bg-[#77736d] text-white'}

function Art({p,hero=false}:{p?:Product;hero?:boolean}) {
  if(hero) return <div className="paper relative h-full min-h-[440px] overflow-hidden bg-[#d8d0c5]"><div className="absolute -left-16 top-10 h-48 w-[75%] -rotate-6 rounded-md bg-[#2e312d] shadow-2xl"><span className="absolute bottom-8 left-12 font-display text-3xl text-[#e6dfd4]">WORKWEAR / 92</span></div><div className="absolute right-[-5%] top-[30%] h-52 w-[72%] rotate-6 rounded-md bg-[#773a2d] shadow-2xl"><span className="absolute left-10 top-10 border-2 border-[#f5f1ed] px-5 py-2 font-display text-2xl text-[#f5f1ed]">WORLD TOUR</span></div><div className="absolute bottom-[-9%] left-[8%] h-60 w-[74%] -rotate-2 rounded-md bg-[#b1a588] shadow-2xl"><div className="mx-auto mt-8 h-24 w-24 rounded-full border-[10px] border-[#31342f]"/></div><div className="absolute bottom-5 right-5 border border-[#2a2a2a] bg-[#f5f1ed] px-3 py-2 font-mono text-[10px] uppercase tracking-widest">Archive lot 0087</div></div>
  return <div className={`paper relative aspect-[4/5] overflow-hidden bg-gradient-to-br ${p?.tone}`}><div className="absolute inset-x-[18%] top-[13%] h-[66%] rounded-t-[42%] rounded-b-lg border border-white/20 bg-black/15 shadow-2xl"><div className="absolute left-1/2 top-0 h-12 w-20 -translate-x-1/2 rounded-b-full border-b border-white/30"/><span className="absolute left-1/2 top-[42%] -translate-x-1/2 whitespace-nowrap font-display text-lg tracking-widest text-white/80">{p?.mark}</span></div><span className="absolute bottom-4 left-4 font-mono text-[9px] uppercase tracking-[.22em] text-white/70">Authenticated archive</span></div>
}
function ProductCard({p,wide=false}:{p:Product;wide?:boolean}) { const [liked,setLiked]=useState(false); return <article className={`${wide?'min-w-[260px] md:min-w-[300px]':''} group`}><div className="relative border border-[#2a2a2a]/20 transition duration-300 group-hover:-translate-y-1 group-hover:shadow-[8px_8px_0_#2a2a2a]"><Link href={`/products/${p.id}`} aria-label={`View ${p.name}`}><Art p={p}/></Link><span className={`absolute right-3 top-3 rounded-full px-2.5 py-1 text-[10px] font-bold uppercase ${badge[p.condition]}`}>{p.condition}</span>{wide&&<span className="absolute left-3 top-3 bg-[#2a2a2a] px-2 py-1 text-[10px] font-bold uppercase tracking-widest text-white">Featured</span>}<button onClick={()=>setLiked(!liked)} aria-label={liked?'Remove from wishlist':'Add to wishlist'} className="absolute bottom-3 right-3 grid h-9 w-9 place-items-center rounded-full bg-[#f5f1ed] shadow"><Heart size={17} fill={liked?'#B55239':'none'} className={liked?'text-[#b55239]':''}/></button></div><div className="border-x border-b border-[#2a2a2a]/20 bg-[#f5f1ed] p-4"><div className="mb-2 flex justify-between gap-2"><p className="font-mono text-[10px] uppercase tracking-[.18em] text-[#77736d]">{p.brand}</p><p className="text-[10px] uppercase text-[#77736d]">{p.category} · {p.size}</p></div><Link href={`/products/${p.id}`} className="font-display font-semibold leading-tight hover:text-[#b55239]">{p.name}</Link><div className="mt-4 flex items-end justify-between"><p className="font-display text-xl font-bold">${p.price.toLocaleString()}.00</p>{p.stock===1&&<p className="text-xs font-bold text-[#b55239]">Only 1 left</p>}</div></div></article> }
function Filter({label,value,set,options}:{label:string;value:string;set:(v:string)=>void;options:string[]}) { return <div className="mb-6"><label className="filter-label">{label}</label><div className="flex flex-wrap gap-2">{options.map(o=><button key={o} onClick={()=>set(o)} className={`border px-2.5 py-1.5 text-xs ${value===o?'border-[#2a2a2a] bg-[#2a2a2a] text-white':'border-[#2a2a2a]/30'}`}>{o}</button>)}</div></div> }

export default function Home(){
 const [menu,setMenu]=useState(false),[filters,setFilters]=useState(false),[category,setCategory]=useState('All'),[size,setSize]=useState('All'),[condition,setCondition]=useState('All'),[brand,setBrand]=useState(''),[maxPrice,setMaxPrice]=useState(2500)
 const [email,setEmail]=useState(''),[sending,setSending]=useState(false),[sent,setSent]=useState(false),[error,setError]=useState('')
 const filtered=useMemo(()=>products.filter(p=>(category==='All'||p.category===category)&&(size==='All'||p.size===size)&&(condition==='All'||p.condition===condition)&&p.brand.toLowerCase().includes(brand.toLowerCase())&&p.price<=maxPrice),[category,size,condition,brand,maxPrice])
 const reset=()=>{setCategory('All');setSize('All');setCondition('All');setBrand('');setMaxPrice(2500)}
 async function subscribe(e:FormEvent){e.preventDefault();setSending(true);setError('');try{const r=await fetch(`${process.env.NEXT_PUBLIC_CONSTRUCTOR_API}/v1/forms/${process.env.NEXT_PUBLIC_PROJECT_ID}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,form:'RetroThread drop alerts'})});if(!r.ok)throw new Error();setSent(true)}catch{setError('Something went wrong. Please try again.')}finally{setSending(false)}}
 const nav=[['Shop','#shop'],['New arrivals','#just-in'],['Sell','#sellers'],['Our standard','#about']]
 return <main><header className="sticky top-0 z-50 border-b border-[#2a2a2a] bg-[#f5f1ed]/95 backdrop-blur"><div className="mx-auto flex h-16 max-w-[1500px] items-center justify-between px-5 lg:px-10"><Link href="/" className="font-display text-xl font-bold">RETRO<span className="text-[#b55239]">THREAD</span></Link><nav className="hidden gap-8 md:flex">{nav.map(n=><a key={n[0]} href={n[1]} className="text-xs font-bold uppercase tracking-widest hover:text-[#b55239]">{n[0]}</a>)}</nav><div className="flex items-center gap-2"><a href="#shop" aria-label="Search products" className="grid h-9 w-9 place-items-center"><Search size={18}/></a><Link href="/cart" aria-label="Shopping cart" className="relative grid h-9 w-9 place-items-center"><ShoppingBag size={19}/><span className="absolute right-0 top-0 grid h-4 w-4 place-items-center rounded-full bg-[#b55239] text-[9px] text-white">0</span></Link><button onClick={()=>setMenu(!menu)} className="grid h-9 w-9 place-items-center md:hidden" aria-label="Toggle menu">{menu?<X/>:<Menu/>}</button></div></div><div className={`absolute inset-x-0 top-16 border-b border-[#2a2a2a] bg-[#f5f1ed] p-6 transition-all duration-500 ease-[cubic-bezier(0.16,1,0.3,1)] md:hidden ${menu?'translate-y-0 opacity-100 pointer-events-auto':'-translate-y-4 opacity-0 pointer-events-none'}`}>{nav.map((n,i)=><a key={n[0]} href={n[1]} onClick={()=>setMenu(false)} style={{transitionDelay:menu?`${i*60}ms`:'0ms'}} className="block border-b border-[#2a2a2a]/20 py-4 font-display text-2xl transition-all">{n[0]}</a>)}</div></header>

 <section className="grid min-h-[calc(100vh-64px)] border-b border-[#2a2a2a] lg:grid-cols-2"><div className="order-2 flex items-center bg-[#2a2a2a] px-6 py-16 text-[#f5f1ed] lg:order-1 lg:px-16"><div className="max-w-2xl"><p className="mb-6 font-mono text-xs uppercase tracking-[.3em] text-[#c7bfb5]">Curated archive · Drop 091</p><h1 className="font-display text-5xl font-bold uppercase leading-[.92] tracking-[-.05em] sm:text-7xl xl:text-[92px]">Own the rarest pieces. <span className="text-[#c76a50]">Wear the story.</span></h1><p className="mt-7 max-w-lg leading-7 text-[#d2cdc6]">Handpicked vintage and streetwear from the world&apos;s best collectors. Shop 8,000+ authenticated items updated daily.</p><div className="mt-9 flex flex-wrap gap-3"><a href="#shop" className="inline-flex items-center gap-2 rounded-md bg-[#f5f1ed] px-6 py-3 text-sm font-bold text-[#2a2a2a]">Start Browsing <ArrowRight size={17}/></a><a href="#sellers" className="rounded-md border border-[#f5f1ed] px-6 py-3 text-sm font-bold">Sell Your Collection</a></div></div></div><div className="order-1 min-h-[48vh] lg:order-2"><Art hero/></div></section>
 <section className="bg-[#8b9a7c] px-5 py-6"><div className="mx-auto grid max-w-[1500px] grid-cols-2 gap-6 lg:grid-cols-4">{[[PackageCheck,'18,500+','Items in Stock'],[Users,'47,000+','Happy Collectors'],[ShieldCheck,'100%','Authenticity Guaranteed'],[Box,'24 Hours','Dispatch Window']].map(([Icon,big,small])=>{const I=Icon as typeof Check;return <div key={String(small)} className="flex items-center gap-3"><I size={23}/><div><p className="font-display text-lg font-bold">{String(big)}</p><p className="text-xs">{String(small)}</p></div></div>})}</div></section>
 <Row id="editors" eyebrow="Curator's desk" title="Editor's Picks This Week" items={products.slice(0,5)}/>
 <section id="shop" className="border-y border-[#2a2a2a] bg-[#e8e1d9] px-5 py-20 lg:px-10"><div className="mx-auto max-w-[1500px]"><div className="mb-10 flex items-end justify-between"><div><p className="eyebrow">The full rack</p><h2 className="section-title">Shop the Archive</h2></div><button onClick={()=>setFilters(!filters)} className="flex items-center gap-2 border border-[#2a2a2a] px-4 py-2 text-sm font-bold lg:hidden"><SlidersHorizontal size={16}/> Filters <ChevronDown size={15}/></button></div><div className="grid gap-8 lg:grid-cols-[240px_1fr]"><aside className={`${filters?'block':'hidden'} h-fit border border-[#2a2a2a]/30 bg-[#f5f1ed] p-5 lg:sticky lg:top-24 lg:block`}><div className="mb-6 flex justify-between"><b>FILTER INDEX</b><button onClick={reset} className="text-xs underline">Reset</button></div><label className="filter-label">Brand search</label><input value={brand} onChange={e=>setBrand(e.target.value)} placeholder="Search brands" className="mb-6 w-full border border-[#2a2a2a]/30 bg-transparent px-3 py-2 text-sm"/><Filter label="Category" value={category} set={setCategory} options={['All','Tops','Bottoms','Outerwear','Accessories','Footwear']}/><Filter label="Size" value={size} set={setSize} options={['All','M','L','XL','30W','32W','10','OS']}/><Filter label="Condition" value={condition} set={setCondition} options={['All','Mint','Excellent','Good','Fair']}/><label className="filter-label">Maximum price · ${maxPrice}</label><input type="range" min="20" max="2500" step="20" value={maxPrice} onChange={e=>setMaxPrice(+e.target.value)} className="w-full accent-[#b55239]"/><button onClick={()=>setFilters(false)} className="mt-6 w-full bg-[#2a2a2a] py-3 text-sm font-bold text-white lg:hidden">Apply Filters</button></aside><div><div className="mb-5 flex justify-between border-b border-[#2a2a2a]/20 pb-3"><p className="font-mono text-xs uppercase tracking-widest">{filtered.length} results</p><p className="text-xs text-[#77736d]">Curated order</p></div>{filtered.length?<div className="grid grid-cols-2 gap-4 md:grid-cols-3 xl:grid-cols-4">{filtered.map(p=><ProductCard key={p.id} p={p}/>)}</div>:<div className="border border-dashed py-24 text-center"><p className="font-display text-2xl font-bold">No pieces match this edit.</p><button onClick={reset} className="mt-4 text-sm font-bold text-[#b55239] underline">Clear all filters</button></div>}</div></div></div></section>
 <Row id="just-in" eyebrow="Fresh inventory" title="Just In" items={[...products].reverse().slice(0,6)}/>
 <section id="about" className="bg-[#2a2a2a] px-5 py-24 text-center text-[#f5f1ed]"><div className="mx-auto max-w-3xl"><ShieldCheck className="mx-auto mb-6 text-[#9baa8c]" size={40}/><p className="eyebrow text-[#bdb5ab]">The RetroThread standard</p><h2 className="font-display text-4xl font-bold uppercase sm:text-6xl">Every thread checked. Every story kept.</h2><p className="mx-auto mt-7 max-w-2xl leading-7 text-[#cfc8c0]">Each listing is reviewed for brand markers, construction, age and condition. Clear grading and seller notes mean the piece that arrives is the piece you expected.</p><a href="#shop" className="mt-8 inline-flex items-center gap-2 border-b pb-1 font-bold">Explore verified pieces <ArrowRight size={16}/></a></div></section>
 <section id="sellers" className="border-b border-[#2a2a2a] px-5 py-20 lg:px-10"><div className="mx-auto max-w-[1500px]"><p className="eyebrow">For independent sellers</p><h2 className="section-title mb-10">A plan for every rack.</h2><div className="grid border-l border-t border-[#2a2a2a] md:grid-cols-3">{[['Explorer','$0 / month',['Up to 10 listings','8% commission','Basic dashboard','Email support']],['Collector','$29 / month',['Unlimited listings','5% commission','Analytics dashboard','Verified seller badge']],['Enterprise','$99 / month',['Unlimited listings','2% commission','Bulk catalog API','Monthly payout guarantee']]].map((t,i)=><article key={t[0] as string} className={`border-b border-r border-[#2a2a2a] p-7 ${i===1?'bg-[#e8e1d9]':''}`}><p className="font-mono text-xs">0{i+1}</p><h3 className="mt-5 font-display text-3xl font-bold">{t[0] as string}</h3><p className="mt-2 text-[#b55239]">{t[1] as string}</p><ul className="my-7 space-y-3">{(t[2] as string[]).map(x=><li key={x} className="flex gap-2 text-sm"><Check size={16}/>{x}</li>)}</ul><a href="#newsletter" className="inline-flex items-center gap-2 font-bold underline">Join as a seller <ArrowRight size={15}/></a></article>)}</div></div></section>
 <section className="bg-[#8b9a7c] px-5 py-10"><div className="mx-auto grid max-w-[1300px] grid-cols-2 gap-8 text-center md:grid-cols-4">{[['8K+','Daily listings'],['4','Condition grades'],['3','Seller plans'],['1','Shared archive']].map(x=><div key={x[1]}><p className="font-display text-4xl font-bold">{x[0]}</p><p className="text-xs uppercase tracking-wider">{x[1]}</p></div>)}</div></section>
 <section className="px-5 py-20 lg:px-10"><div className="mx-auto max-w-[1500px]"><p className="eyebrow">Worn and vouched for</p><h2 className="section-title mb-10">Collector Notes</h2><div className="grid border-l border-t border-[#2a2a2a]/30 md:grid-cols-3">{[['SC','Sarah Chen','Collector',"Found a 1987 Champion sweatshirt I had been hunting for 3 years. The photos were honest and the condition was exactly as described."],['MR','Marcus Rodriguez','Reseller','The catalog tools are smooth. Managing 200 items is seamless, shipping labels generate quickly and payments are clear.'],['JW','Jenna Wilson','Vintage Enthusiast',"Every piece tells a story. The seller notes and provenance details add so much. This is collecting with confidence."]].map(t=><blockquote key={t[0]} className="border-b border-r border-[#2a2a2a]/30 p-7"><div className="mb-7 grid h-14 w-14 place-items-center rounded-full bg-[#e8e1d9] font-bold text-[#b55239]">{t[0]}</div><p className="font-display text-lg leading-7">“{t[3]}”</p><footer className="mt-7 text-sm"><b>{t[1]}</b><br/><span className="text-[#77736d]">{t[2]}</span></footer></blockquote>)}</div></div></section>
 <section id="newsletter" className="border-y border-[#2a2a2a] bg-[#b55239] px-5 py-14 text-[#f5f1ed]"><div className="mx-auto flex max-w-[1200px] flex-col items-center justify-between gap-8 md:flex-row"><div><p className="font-mono text-xs uppercase tracking-[.2em]">Never miss the find</p><h2 className="mt-2 font-display text-3xl font-bold">Drops, restocks and saved search alerts.</h2></div>{sent?<p className="font-bold">✓ Mensaje enviado — te contactaremos pronto</p>:<form onSubmit={subscribe} className="w-full max-w-lg"><div className="flex"><label className="sr-only" htmlFor="email">Email address</label><input id="email" required type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@email.com" className="min-w-0 flex-1 border border-[#f5f1ed] bg-transparent px-4 py-3 placeholder:text-[#ead1ca]"/><button disabled={sending} className="bg-[#f5f1ed] px-5 py-3 font-bold text-[#2a2a2a]">{sending?'Enviando…':'Join the list'}</button></div>{error&&<p className="mt-2 text-sm">{error}</p>}</form>}</div></section>
 <footer className="bg-[#2a2a2a] px-5 py-14 text-[#f5f1ed] lg:px-10"><div className="mx-auto grid max-w-[1500px] gap-10 md:grid-cols-[2fr_1fr_1fr_1fr]"><div><p className="font-display text-2xl font-bold">RETRO<span className="text-[#c76a50]">THREAD</span></p><p className="mt-4 max-w-xs text-sm leading-6 text-[#aaa39b]">Authenticated vintage and streetwear, sourced from independent collectors.</p></div>{[['DISCOVER',['Shop archive','Just in','Editor picks']],['SELL',['Seller plans','Submit collection','Seller tools']],['STANDARD',['Condition guide','Authenticity','Our process']]].map(g=><div key={g[0] as string}><p className="mb-4 font-mono text-xs tracking-widest text-[#aaa39b]">{g[0] as string}</p>{(g[1] as string[]).map((x,i)=><a key={x} href={i===0?'#shop':i===1?'#just-in':'#about'} className="mb-3 block text-sm hover:text-[#c76a50]">{x}</a>)}</div>)}</div><div className="mx-auto mt-14 flex max-w-[1500px] flex-col justify-between gap-3 border-t border-white/20 pt-6 text-xs text-[#88817a] sm:flex-row"><p>© 2026 RetroThread. Archive responsibly.</p><p>Built for the next life of great clothing.</p></div></footer>
 </main>
}
function Row({id,eyebrow,title,items}:{id:string;eyebrow:string;title:string;items:Product[]}){return <section id={id} className="px-5 py-20 lg:px-10"><div className="mx-auto max-w-[1500px]"><p className="eyebrow">{eyebrow}</p><h2 className="section-title mb-8">{title}</h2><div className="hide-scrollbar flex gap-5 overflow-x-auto pb-5">{items.map(p=><ProductCard key={p.id} p={p} wide/>)}</div></div></section>}
